config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :friendships
  resources :tasks

  resources :users do
    resources :tasks
  end

  

  root 'sessions#new'

  post '/add_friend' => 'friendships#add_friend'

  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/search' => 'users#index'
  post '/search'=> 'users#index'


  post '/accept_friend'  => 'friendships#accept_friend'
  post '/decline_friend' => 'friendships#decline_friend'

  post '/users/:doer_id/request_task/:task_id' => "tasks#request_task", as: "request_task"
  post 'accept_task/:task_id' => 'tasks#accept_task', as: "accept_task"
  post 'decline_task/:task_id' => 'tasks#decline_task', as: "decline_task"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :friendships
  has_many :friends,
  :through => :friendships

  has_many :tasks
  has_many :missions,
  :class_name => 'Task', foreign_key: :doer_id


  has_attached_file :avatar, styles: {
      small: "160x160",
      medium: "200x200>",
      thumb: "100x100>"
      }#, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates :username, presence: true, uniqueness: true, length: { maximum: 50 }
  validates :password, confirmation: true, presence: true, length: { in: 6..20 }
  validates :password_confirmation, presence: true, length: { in: 6..20 }

  def is_friends_with?(user)
    Friendship.exists?(self, user)
  end

  def status_with(user)
    return "NONE" unless Friendship.exists?(self, user)
    Friendship.find_by(user_id: user.id, friend_id: id).status
  end

  def accepted_friends
    Friendship.where(user: id, status: :accepted).map(&:friend)
  end

  def self.friend_level(for_doer:, with_creator:)
    Task.accepted.where(doer_id: for_doer, user_id: with_creator).sum(:points)
  end

  # ashley = @user
  #
  # Alby = current_user
  #
  # mypoints = friend_level for_doer: current_user, with_creator: @user
  #
  # herpoints = friend_level for_doer: @user, with_creator: current_user
  #
  # ashleys_debt = mypoints / herpoints


  # def points_with(user)
  #   Task.where(doer_id: user.id, user_id: self.id).accepted.map(&:points).inject(:+)
  # end
  #
  # def points_for(user)
  #   Task.where(doer_id: self.id, user_id: user.id).accepted.map(&:points).inject(:+)
  #   tasks.accepted.where()
  # end

  def points
    Task.where(doer_id: self.id).accepted.map(&:points).inject(:+)
  end
  #
  # def top_three_friends
  #   self.friends.sort{|a,b| a.points_for(self) <=> b.points_for(self)}.first(3)
  # end


  def top_friends_that_you_earn_points_from(limit)
    missions.accepted.group(:creator).sum(:points).sort_by { |name, point| point}.reverse[0..limit]
  end

  def top_friends_that_earn_points_from_you(limit)
    tasks.accepted.group(:doer).sum(:points).sort_by { |name, point| point}.reverse[0..limit]
  end

  def friend_comparison(user, limit)


  end


  #ed's fix in the editor
  # missions.accepted.group(:creator).sum(:points).sort_by {|hsh| -hsh.values.first}[0..limit]
  #ed's version in terminal
  # s.missions.accepted.group(:creator).sum(:points).map { |k, v| {k.username => v}}.sort_by {|hsh| -hsh.values.first}

  # after_action :filter
  #   def filter
  # if current_user == owner
  #   dont filter anything
  # elsif current_user friends owner
  #   show some things
  # else
  #   show few things
  # end
  # end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:show, :index]
  before_action :set_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    user.save!
    if user.save!
      session[:user_id] = user.id
      redirect_to task_path
    else
      redirect_to '/signup'
    end
  end

  def show
    @user_pending_tasks = Task.where(status: "pending", doer_id: current_user.id)
    @this_user_points = User.friend_level(for_doer: current_user, with_creator: @user)
    @current_user_points = User.friend_level(for_doer: @user, with_creator: current_user)
  end

  def index
    @users = User.where("username LIKE ?", "#{params[:term]}")
  end

private

  def build_user
    @user = User.new(user_params)
  end

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def point_ratio(points1,points2)
    return points1 if points2 == 0
    return points2 if points1 == 0
    points1 >= points2 ? points1/points2 : points2/points1
  end

end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<!--User Index Page -->

<body class="index-page">

<div class="search">
  <h3>Showing search results for "<%= params[:term] %>"</h3>
</div>
  <div class="card">

    <div class="yourresults animated finite bounceInDown">
        <h1>Your Search Results...</h1>
    </div>


    <% @users.each do |u|%>
     <div class="col-sm-6 col-md-4 col-md-offset-4">
       <div class="tn animated finite fadeInDown">
            <div class="caption">
              <p>
                <% if u.avatar.blank? %>
                  <%= image_tag("http://vignette4.wikia.nocookie.net/dragcave/images/6/6e/No_avatar.jpg/revision/latest?cb=20140427211725", class: "img-responsive center-block", height: 200) %>
                <% else %>
                  <%= image_tag u.avatar.url(:medium), class: "img-responsive center-block", height: 200 %>
                <% end %>
              </p>
              <hr>
              <% case current_user.status_with(u) %>
                <% when "NONE" %>
                  <%= u.username %>
                  <p class="add-friend">
                    <%= button_to 'Add Friend', add_friend_path(friend: u.id), class: "btn btn-danger btn-sm animated infinite tada"%>
                  </p>
                  <p>
                <% when "accepted" %>
                  <p><%= link_to u.username, u %></p>
                  <p class= "remove-friend">
                    <%= link_to 'remove friend', friendship_path(u), :method => :delete %>
                  </p>
                <% when "pending" %>
                  <%= u.username %><br>
                  <span>Friendship Requested</span>
                <% end %>
                </p>
            </div>
        </div>
      </div>
    <% end %>
  </div>


<body background="http://cdn.mysitemyway.com/etc-mysitemyway/backgrounds/legacy-previews/backgrounds/watercolor-grunge/watercolor-grunge-000053-metallic-gold.jpg">

app/views/users/new.html.erb
<!--Sign up form for :user that includes username and password-->

<body class="signuppic">

  <div class="friendl">
    <p>
      FriendLevel
    </p>
  </div>

<div class="col-md-4 col-xs-12 col-md-offset-1 col-xs-offset-0">
<div class="signup animated infinite tada">
  <h2>Signup!</h2>
</div>


<div class="signuprow">
  <!-- <div class="col-md-12 col-xs-12 col-md-offset-0 col-xs-offset-0"> -->
    <%= form_for @user, url: '/users', html: { multipart: true } do |f| %>

    <%= f.label :Share_A_Friendly_Pic! %>
    <%= f.file_field :avatar %><br>

    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control'  %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control'  %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control'  %><br>

    <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>
<!-- </div> -->
</body>

app/views/users/show.html.erb
<body class="showpage">

<section>
  <div class="profileinfo">

<section>

  <div class="userinfo">
    <br>
      <div class="polaroid2"><br>
        <% if @user.avatar.blank? %>
          <%= image_tag("http://vignette4.wikia.nocookie.net/dragcave/images/6/6e/No_avatar.jpg/revision/latest?cb=20140427211725", class: "img-responsive") %>
        <% else %>
          <%= image_tag @user.avatar.url(:medium), class: "img-responsive" %>
        <% end %>
      </div>
  <div class="welcome">
    <% if current_user == @user %>
      <h3><b>WELCOME, <%= @user.username.upcase %>!</b></h3>
    <% else %>
      <h3><b><%= @user.username.upcase %></b></h3>
    <% end %>
  </div>

</div>
</section>

<section>
  <div class="otherinfo">
    <div class="heading">

      <% if current_user != @user %>
        <% if @current_user_points > @this_user_points %>
        <h3 class="fl">FRIENDLEVEL <span class="glyphicon glyphicon-triangle-top"></span><%= point_ratio @current_user_points, @this_user_points%>%</h3>
          There is a <b><%= @current_user_points %>/<%= @this_user_points %></b> Point Ratio.

          <% elsif @current_user_points == @this_user_points %>
          <h3 class="fl">FRIENDLEVEL EQUAL </h3>
            There is a <%= @current_user_points %>/<%= @this_user_points %> Point Ratio.

        <% else %>
        <h1 class="fl">FRIENDLEVEL <span class="glyphicon glyphicon-triangle-bottom"></span> <%= point_ratio @current_user_points, @this_user_points%>%</h1>
          There is a <strong><%= @current_user_points %>/<%= @this_user_points %></strong> Point Ratio.
        <% end %>

<br><div class="progress" style="width:500px;margin-bottom:0px;margin-top:20px;">
  <div class="progress-bar" role="progressbar" aria-valuenow="<%= @current_user_points %>" aria-valuemin="0" aria-valuemax="9000" style="min-width: 15em; width: 2%; background: #b30000;">
    <%= @current_user_points %>
  </div>
</div>
<div class="cup">
  You have accumulated this many points for doing tasks for <%= @user.username %>.
</div><br>

<div class="progress" style="width:500px;margin-bottom:0px;margin-top:20px;">
  <div class="progress-bar" role="progressbar" aria-valuenow="<%= @this_user_points %>" aria-valuemin="0" aria-valuemax="9000" style="min-width: 16em; width: 2%; background: #b30000;">
    <%= @this_user_points %>
  </div>
</div>
<div class="tup">
   <%= @user.username %> has accumulated this many points for doing tasks for you.
</div><br><br>
<% end %>


    </div>

  </div>
</section>

</div>
</section>



<section>
<div class="second">

<section>

    <div class="overlay"></div>
      <div class="friendlist">
        <h3> Top Friends Who Do The Most For You </h3>
      </div>
    <% @user.top_friends_that_earn_points_from_you(3).each do |friend|%>
    <div class="polaroid"><br>
      <% if friend.first.avatar.blank? %>
        <%= image_tag("http://vignette4.wikia.nocookie.net/dragcave/images/6/6e/No_avatar.jpg/revision/latest?cb=20140427211725", class: "img-responsive frilistpic") %>
      <% else %>
        <%= image_tag friend.first.avatar.url(:medium), class: "img-responsive" %>
      <% end %>
      <b>
        <%= friend[0].username %>
      </b><br>
      Earned <b><%= friend[1] %></b> Points<br>From You!
    </div><br>
    <% end %>

  </section>

  <section>
    <div class="friendlist2">
      <h3> Top Friends Who You Do The Most For </h3>
    </div>
    <% @user.top_friends_that_you_earn_points_from(3).each do |friend|%>
    <div class="polaroid"><br>
      <% if friend.first.avatar.blank? %>
        <%= image_tag("http://vignette4.wikia.nocookie.net/dragcave/images/6/6e/No_avatar.jpg/revision/latest?cb=20140427211725", class: "img-responsive frilistpic") %>
      <% else %>
        <%= image_tag friend.first.avatar.url(:medium), class: "img-responsive" %>
      <% end %>
      <b>
        <%= friend[0].username %>
      </b><br>
      Gave You <b><%= friend[1] %></b> Points!<br><br>
    </div>
    <% end %>

  </div>
  </section>

</div>
</section>


<section>
  <div class="first">
  <!-- <div class="container-1"> -->
    <div class="list1"><h1>Tasks I've Created</h1>
    </div>
      <% @user.tasks.each do |task| %>
      <% if task.status != "accepted" %>
        <div class="postit col-md-4 col-sm-6 col-md-offset-0" >
          <div class="usertask">
            <div class="title">
              <b>
                <%= task.title %><br>
              </b>
            </div>
            <%= task.details %><br>
            <%= task.due_date.strftime("%b. %d, '%y - %I:%M %p")%><br><br>
            <b>
              Worth <%= task.points %> Point(s)<br>
            </b>
            <% if current_user.id == task.user_id %>
              (<%= link_to 'Delete', task, :method => :delete %>)
            <% else %>
              <%= link_to 'Pick up this task', request_task_path(current_user, task), :method => :post %>
              <%#= link_to 'Approve this task', accept_task_path(task.id), :method => :post %>
            <% end %>
          </div>
        </div>
        <% end %>
      <% end %>
</div>
</section>

<section>
  <div class="container-2">

    <% if current_user == @user %>
    <div class="pendingcom">
      <h1> Tasks Pending My Completion </h1>
    </div>
        <% @user_pending_tasks.each do |task| %>
            <div class="postit2 col-md-4 col-sm-6 col-md-offset-0" >
            <u><i>I'm doing this for: <b><%= task.creator.username %></b></i></u><br>
            <div class="title">
            <b>
              <%= task.title %><br>
            </b>
            </div>
            <%= task.details %><br>
            <%= task.due_date.strftime("%b. %d, '%y - %I:%M %p") %><br><br>
            <b>
              Worth <%= task.points %> Point(s)
            </b>
            </div>
        <% end %>

      <% end %>
    </div>
  </section>

</body>