config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :friendships
  resources :tasks

  resources :users do
    resources :tasks
  end

  

  root 'sessions#new'

  post '/add_friend' => 'friendships#add_friend'

  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/search' => 'users#index'
  post '/search'=> 'users#index'


  post '/accept_friend'  => 'friendships#accept_friend'
  post '/decline_friend' => 'friendships#decline_friend'

  post '/users/:doer_id/request_task/:task_id' => "tasks#request_task", as: "request_task"
  post 'accept_task/:task_id' => 'tasks#accept_task', as: "accept_task"
  post 'decline_task/:task_id' => 'tasks#decline_task', as: "decline_task"
end

app/views/layouts/_form.html.erb
<% if current_user %>
  <div class="modal fade" id="new_task" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">New Task</h4>
        </div>
        <div class="modal-body">
          <div class="container">
            <div class="row">
              <table class="col-md-7">
                <div class = "newtaskform">
                  <div class="container">
                    <div class="row">
                      <div class="col-md-4 col-md-offset-1">

                        <%= form_for(:task, url: user_tasks_path(current_user)) do |f| %>
                          <span class="error"><%= flash[:error] %><br></span>

                          <%= f.label :title %>
                          <%= f.text_field :title, class: "form-control", maxlength: 14, placeholder: "e.g.'Bring me dinner' - 15 character limit" %><br>

                          <%= f.label :details %>
                          <%= f.text_field :details, class: "form-control", maxlength: 23, placeholder: "e.g. 'I want sushi' - 23 character limit" %><br>

                          <%= f.label :due_date %>
                          <%= f.datetime_field :due_date, class: "form-control" %><br>

                          <%= f.label :points %>
                          <%= f.select "points", options_for_select((100..1000).step(100)), :class => 'selectpicker' %>
                          <br><br>
                          <%= f.submit "Create Task", class: "btn btn-danger" %>

                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>


                <script>
                  $('#task_points').selectpicker();
                </script>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_pending_tasks.html.erb
<% if current_user %>
  <div class="modal fade" id="pending_tasks" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Pending Tasks</h4>
        </div>
        <div class="modal-body">
            <div class="row">
              <div>
                <% if current_user %>
                <div class="col-sm-7">
                  <% pending_tasks.each do |task| %>
                    Did <b><%= task.doer.username.upcase %></b> complete <b><%= task.title %></b> for <b><%= task.points %></b> point(s)?
                </div>
                <div class="col-sm-5 approve-task">
                 <%#= task.due_date.strftime("%b. %d, '%y - %I:%M %p") %>
                  <div><%= button_to 'Completed', accept_task_path(task.id), :method => :post,class: "btn btn-danger btn-sm"%></div>
                  <div><%= button_to 'Reject', decline_task_path(task.id), :method => :post, class: "btn btn-danger btn-sm" %></div>
                  <% end %>
                <% end %>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FriendLevel</title>
  <%= csrf_meta_tags %>



  <!-- Latest compiled and minified CSS -->


  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Mogra|Oregano|Paprika|Salsa" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <!-- Animate -->
  <link rel="stylesheet" href="http://s.mlcdn.co/animate.css"></link>
</head>

<!-- body begins -->
<body>
  <!-- static nav bar -->
  <header class="navbar navbar-fixed-top my-navbar">
    <% if current_user %>
      <div class="dropdown">
        <button class="btn btn-danger btn-sm dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          <span class="glyphicon glyphicon-align-justify" aria-hidden="true"></span> FRIENDLEVEL
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
          <div class="test2">
            <li><%= link_to "My Profile", current_user, id: "color"%></li>
            <li><%= link_to "Tasks Feed", user_tasks_path(current_user), id: "color"%></li>
            <li><%= link_to "Logout", '/logout', id: "color"%></li>
          </div>
        </ul>
      </div>


<p class="navlogo" text-align:center>
  FriendLevel
</p>


    <!-- search bar -->
    <nav class= "navbar-right">
      <div class="test">
        <button type="button" class="btn btn-new btn-sm animated infinite pulse" data-toggle="modal" data-target="#new_task">
          <b>+ New Task</b>
        </button>
        <%= form_tag search_path, class: "search-form" do %>
        <%= search_field_tag :term,'', class: "search-bar" %>
        <%= submit_tag "Go!", class: "btn btn-danger btn-sm" %>
        <% end %>
      </div>
    </nav>

    <!-- Button trigger modal for Friend Requests -->
    <div class="requests">
      <button type="button" class="btn btn-new btn-sm" data-toggle="modal" data-target="#friend_request">

        Friend Requests
          <% if pending_friends != 0 %>
          <span class="badge"><%= pending_friends.count %></span>
        <% end %>
      </button>
      <button type="button" class="btn btn-new btn-sm" data-toggle="modal" data-target="#pending_tasks">
        View Pending Tasks
        <% if pending_tasks != 0 %>
          <span class="badge"><%= pending_tasks.count %></span>
        <% end %>

      </button>

    <% else %>
      <nav class= "navbar navbar-fixed-top navbar-default">
        <%= link_to "FRIENDLEVEL", root_path, id: "logo"%>
        <%= link_to 'Signup', signup_path, id: "logo"%>
        <%= link_to 'Login', root_path, id: "logo"%>

      <nav class= "navbar-right">
        <div class="slogan">
          <p>
            "Turn Your Needs Into Deeds."
          </p>
        </div>
      </nav>
    </nav>
    <% end %>

  </header>

  <!-- Modal for Friend Requests-->
  <% if current_user %>
  <div class="modal fade" id="friend_request" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Your Friend Requests</h4>
        </div>
        <div class="modal-body">
          <div class="container">
            <div class="row">
              <table class="col-md-7">
                <% current_user.friends.each do |friend| %>
                <tr>
                  <% if friend.friendships.where(status: 'requested', friend_id: current_user.id) != [] %>
                  <td class="col-md-4" height="50"><b><%= friend.username %></b></td>
                  <td class="col-md-4" height="50"><%= button_to 'Accept', accept_friend_path(friend: friend.id), class: "btn btn-danger btn-sm"%></td>
                  <td class="col-md-4" height="50"><%= button_to 'Decline', decline_friend_path(friend: friend.id), class: "btn btn-danger btn-sm"%></td>
                  <% end %>
                </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class='page-body'>
  <%= yield %>
</div>

<%= render partial: "/layouts/pending_tasks" %>
<%= render partial: "layouts/form", locals: { task: @task } %>

</body>
</html>